# Generated by Django 5.1.3 on 2024-11-23 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_first_shipment', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время первой отправки')),
                ('date_time_end_shipment', models.DateTimeField(auto_now=True, verbose_name='Дата и время первой отправки')),
                ('status', models.CharField(choices=[('Завершена', 'завершена'), ('Создана', 'создана'), ('Запущена', 'запущена')], default='Создана', max_length=10, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['date_time_first_shipment', 'status'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='Введите тему письма', max_length=250, verbose_name='Тема письма')),
                ('body', models.TextField(help_text='Введите тело письма', verbose_name='Тело письма')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Введите Email', max_length=254, verbose_name='Email получателя')),
                ('fio', models.CharField(help_text='Введите фамилию, имя, отчество', max_length=300, verbose_name='Ф.И.О.')),
                ('comment', models.TextField(blank=True, help_text='Введите комментарий', null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Получатель рассылки',
                'verbose_name_plural': 'Получатели рассылки',
                'ordering': ['fio'],
            },
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Введите имя отправителя', max_length=250, null=True, verbose_name='Имя отправителя')),
                ('email', models.EmailField(help_text='Введите email отправителя', max_length=254, verbose_name='Email отправителя')),
                ('organization', models.CharField(blank=True, help_text='Введите название организации', max_length=300, null=True, verbose_name='Организация')),
            ],
        ),
        migrations.CreateModel(
            name='AttemptMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_attempt', models.DateTimeField(auto_now=True, verbose_name='Дата и время попытки')),
                ('status', models.CharField(choices=[('Успешно', 'успешно'), ('Не успешно', 'не успешно')], default='Не успешно', max_length=11, verbose_name='Статус')),
                ('mail_server_response', models.TextField(verbose_name='Ответ почтового сервера')),
                ('mailing', models.ForeignKey(help_text='Введите рассылку', on_delete=django.db.models.deletion.CASCADE, related_name='attemptmailings', to='sending_messages.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
                'ordering': ['date_time_attempt', 'status'],
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(blank=True, help_text='Введите сообщение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailings', to='sending_messages.message', verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='recipients',
            field=models.ManyToManyField(to='sending_messages.recipient'),
        ),
    ]
