# Generated by Django 5.1.3 on 2024-12-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sending_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sender',
            options={'ordering': ['name'], 'verbose_name': 'Отправитель', 'verbose_name_plural': 'Отправители'},
        ),
    ]
