# Generated by Django 5.1.3 on 2024-12-18 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sending_messages', '0003_alter_message_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='Укажите отправителя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailings', to='sending_messages.sender', verbose_name='Отправитель'),
        ),
    ]
