# Generated by Django 5.1.3 on 2024-12-27 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sending_messages', '0007_mailing_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Sender',
        ),
    ]
