# Generated by Django 5.1.3 on 2024-12-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending_messages", "0009_remove_attemptmailing_sending_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attemptmailing",
            name="count_messages",
            field=models.PositiveIntegerField(default=0, verbose_name="Счетчик отправленных сообщений"),
        ),
    ]
